### PR TITLE
moved the package data inside and included it

### PR DESCRIPTION
**Pull request by andyreagan**
this should get those data files loaded from pip

### CODE REVIEW

**Comment by andyreagan** [comment]
I pushed this up to pypi as 0.0.2

**Comment by jakerylandwilliams** [comment]
Awesome, just merged! Will try 0.0.2 now.

---

Jake Ryland Williams, Ph.D.
Postdoctoral Researcher
School of Information
University of California, Berkeley

## jakerylandwilliams[at]berkeley[dot]edu

**Comment by jakerylandwilliams** [comment]
Dang. Just tried on two computers and got the same error:

```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File
```

"/private/var/folders/h3/g59cz2m52v76sz23mw551s8r0000gn/T/pip-build-2Fzui0/partitioner/setup.py",
line 19, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/Users/bigmac/anaconda/lib/python2.7/codecs.py", line 884, in
open
        file = **builtin**.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory:
'/private/var/folders/h3/g59cz2m52v76sz23mw551s8r0000gn/T/pip-build-2Fzui0/partitioner/README.md'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in
/private/var/folders/h3/g59cz2m52v76sz23mw551s8r0000gn/T/pip-build-2Fzui0/partitioner

not sure what's going on with this one---any ideas?

---

Jake Ryland Williams, Ph.D.
Postdoctoral Researcher
School of Information
University of California, Berkeley

## jakerylandwilliams[at]berkeley[dot]edu

**Comment by andyreagan** [comment]
Okay, I'll have to give it another go

## 

Andy Reagan
Department of Mathematics and Statistics
The University of Vermont
16 Colchester Ave.
Burlington, VT 05405
andy@andyreagan.com

**Comment by andyreagan** [comment]
I fixed it!

## 

Andy Reagan
Department of Mathematics and Statistics
The University of Vermont
16 Colchester Ave.
Burlington, VT 05405
andy@andyreagan.com

**Pull request merged**
